# Generated by Django 5.2 on 2025-04-28 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("url", models.URLField(unique=True)),
                ("body", models.TextField()),
                ("category", models.CharField(max_length=100)),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                ("likes", models.IntegerField(default=0)),
                ("author", models.CharField(default="不明", max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="TrendArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("site", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=300)),
                ("url", models.URLField()),
                ("author", models.CharField(blank=True, max_length=100, null=True)),
                ("likes", models.IntegerField(default=0)),
                ("body", models.TextField(blank=True, null=True)),
                ("tags", models.JSONField(default=list)),
                ("scraped_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="FavoriteArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField()),
                ("title", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=100)),
                ("body", models.TextField(blank=True)),
                ("date", models.CharField(blank=True, max_length=100)),
                ("author", models.CharField(blank=True, max_length=100)),
                ("likes", models.IntegerField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
